# Generated by Django 3.2.4 on 2021-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210625_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
